feat: add skip-images flag feature
mendersoftware/app-update-module pull request #74
Opened 2024-11-04 14:28 UTC by DamKast

## Description

It would be very usefull having the possibility to skip including images. That means give to docker compose the responsibility to pull the required images through the network directly from the target device.

This fix modifies the metadata:
If the skip-images flag is set, the metadata will include `images_urls` but not the `images` shas.
When the artifact is installed on the target, the app script will look for the `images.tar.gz` file but since it is not included in the artifact, it will not load any image.
The `images_urls` is used for the clean_up function.

https://hub.mender.io/t/suggestion-add-a-skip-images-option-to-app-update-module/7268

2024-12-13 08:15 UTC, DamKast commented
@merlin-northern Do you want to have a look at this?

2025-01-08 09:23 UTC, lluiscampos requested changes
Hello @DamKast and thank you for your contribution. As @merlin-northern is already busy with other contributions, I will be reviewing your work :smiley: 

By design, we want this update module to **not pull** images, but the module actually will pull an image needed by the manifest if it is not found in the Artifact.

We can have the feature that you want to add, so that it can be used for testing or on devices where network is fully reliable, but we should do it in a backwards compatible way, piggybacking on the behavior that I just described.

Your current proposed changes are conditionally generating (and then decompressing) `images.tar.gz` file in the Artifact. In other words, you have both modified the generator and the update module so the the file is added or not and expected or not. But it should be possible to do it simpler by creating a dummy/empty `images.tar.gz` in the generator, and then the module should not require much changes, it will decompress an empty file, not load any image, and then just start the composition (which will indirectly pull the images).

Can you rework the PR to get something similar to that?

2025-01-27 06:36 UTC, DamKast commented
Hey @lluiscampos,
Thanks for your suggestion, I agree that the simplest possible solution is always the best.
Unfortunately, if I only modify the generator script by creating an empty `images.tar.gz`, the cleanup stage in the app update script will not work properly.

As you can see in the following snippet, urls for the images are only added to the `application_name/images/` folder if the url-new.txt files are in it.

```
    mkdir -pv "${PERSISTENT_STORE}/${application_name}"/images
    rm -vf "${PERSISTENT_STORE}/${application_name}"/images/*
    for image_dir in "${temp_dir}/images/"*; do
        echo "scanning ${image_dir}"
        url_current=$(cat "${image_dir}/url-current.txt")
        url_new=$(cat "${image_dir}/url-new.txt")
        sha_new=$(cat "${image_dir}/sums-new.txt")
        deep_delta=""
        if test -f "${image_dir}/deep_delta"; then
            deep_delta=deep_delta
        fi
        MODULE_TMPDIR="${temp_dir}" OPTIONS="${deep_delta}" $app_sub_module LOAD "${application_name}" "${url_new}" "${image_dir}/image.img" "${url_current}"
        # and the sub module deals with proper image loading
        # we save the image urls and shasums in order to be able to clean up
        echo "${url_new}" >> "${PERSISTENT_STORE}/${application_name}"/images/urls
        echo "${sha_new}" >> "${PERSISTENT_STORE}/${application_name}"/images/shas
    done
```

And the `urls` file is needed if you want the cleanup to work.
```
clean_up() {
    local app_dir="$1"

    if test -f "$app_dir"/images/urls; then
        xargs -I{} $app_sub_module DELETE {} < "$app_dir"/images/urls
    fi
}
```

Let me know what you think about that.

2025-01-27 08:07 UTC, DamKast commented
Herre is the log when I try to install the artifact with an empty `image.tar.gz`

```
 mender-update[719]: record_id=5 severity=info time="2025-Jan-24 15:24:21.835368" name="Global" msg="Running Mender client 4.0.4"
 mender-update[719]: record_id=6 severity=info time="2025-Jan-24 15:24:21.835761" name="Global" msg="Deployment with ID a3e61006-d5dd-42dc-b357-62d3012a25ba started."
 mender-update[719]: record_id=7 severity=info time="2025-Jan-24 15:24:21.837828" name="Global" msg="Sending status update to server"
 mender-update[719]: record_id=8 severity=info time="2025-Jan-24 15:24:23.987015" name="Global" msg="Installing artifact..."
 mender-update[719]: record_id=9 severity=info time="2025-Jan-24 15:24:24.067112" name="Global" msg="Sending status update to server"
 mender-update[719]: record_id=10 severity=info time="2025-Jan-24 15:24:25.587958" name="Global" msg="Update Module output (stdout): decompressing images"
 mender-update[719]: record_id=11 severity=info time="2025-Jan-24 15:24:25.603322" name="Global" msg="Update Module output (stdout): images/"
 mender-update[719]: record_id=12 severity=info time="2025-Jan-24 15:24:25.604521" name="Global" msg="Update Module output (stdout): decompressing manifests"
 mender-update[719]: record_id=13 severity=info time="2025-Jan-24 15:24:25.612550" name="Global" msg="Update Module output (stdout): manifests/"
 mender-update[719]: record_id=14 severity=info time="2025-Jan-24 15:24:25.613088" name="Global" msg="Update Module output (stdout): manifests/docker-compose.yaml"
 mender-update[719]: record_id=15 severity=info time="2025-Jan-24 15:24:25.614336" name="Global" msg="Update Module output (stdout): unpacking images"
 mender-update[719]: record_id=16 severity=info time="2025-Jan-24 15:24:25.614608" name="Global" msg="Update Module output (stdout): unpacking /var/lib/mender/modules/v3/payloads/0000/tree/tmp/images/*"
 mender-update[719]: record_id=17 severity=info time="2025-Jan-24 15:24:25.617450" name="Global" msg="Update Module output (stderr): cat: '/var/lib/mender/modules/v3/payloads/0000/tree/tmp/images/*/url-new.txt': No such file or directory"
 mender-update[719]: record_id=18 severity=error time="2025-Jan-24 15:24:25.618480" name="Global" msg="Process returned non-zero exit status: ArtifactInstall: Process exited with status 1"
 mender-update[719]: record_id=19 severity=info time="2025-Jan-24 15:24:25.688108" name="Global" msg="Sending status update to server"
 mender-update[719]: record_id=20 severity=info time="2025-Jan-24 15:24:26.977048" name="Global" msg="Deployment with ID a3e61006-d5dd-42dc-b357-62d3012a25ba finished with status: Failure"
```

2025-02-04 13:09 UTC, lluiscampos commented
@DamKast I think you are right.

I don't know how to best solve this: I still think that your original design is a big design change but on the low level I agree with you that it is not that easy to fix with minimal changes.

I need some more time to attempt a fix on my side :mag_right:

2025-02-23 19:41 UTC, lluiscampos commented
Hi @DamKast :wave: I apologize that this is taking so much time on my end.

I made it work with an empty `images.tar.gz` with these two changes.

On the one hand, I modified the for loops in the the **original** update module to use `find` instead. This way it won't wrongly attempt to access `images/*` when bash cannot expand the `*`.

```
diff --git a/src/app b/src/app
index a630ea9..2cff52d 100755
--- a/src/app
+++ b/src/app
@@ -157,7 +157,7 @@ handle_artifact() {
     $tar_decompress_cmd "$1"/manifests.tar.gz -C "$temp_dir"
 
     echo "unpacking images"
-    for image_dir in "${temp_dir}/images/"*; do
+    for image_dir in $(find "${temp_dir}/images" -mindepth 1 -maxdepth 1 -type d 2>/dev/null); do
         echo "unpacking $image_dir"
         url_new=$(cat "${image_dir}/url-new.txt")
         url_current=$(cat "${image_dir}/url-current.txt")
@@ -202,7 +202,7 @@ handle_artifact() {
     fi
     mkdir -pv "${PERSISTENT_STORE}/${application_name}"/images
     rm -vf "${PERSISTENT_STORE}/${application_name}"/images/*
-    for image_dir in "${temp_dir}/images/"*; do
+    for image_dir in $(find "${temp_dir}/images" -mindepth 1 -maxdepth 1 -type d 2>/dev/null); do
         echo "scanning ${image_dir}"
         url_current=$(cat "${image_dir}/url-current.txt")
         url_new=$(cat "${image_dir}/url-new.txt")
```

:point_up: In my opinion such a change is a bug fix and can be added to the module independently of this feature request.

And then on the other hand tweaking a bit the module generator **from this PR** to add the empty file:
```
diff --git a/gen/app-gen b/gen/app-gen
index 4a65a00..6077a4d 100755
--- a/gen/app-gen
+++ b/gen/app-gen
@@ -243,9 +243,7 @@ temp_dir="$(mktemp -d)"
     echo "cant get the temporary directory" >&2
     show_help_and_exit_error
 }
-if [ "$skip_images" == "false" ]; then
-    mkdir "${temp_dir}/images"
-fi
+mkdir "${temp_dir}/images"
 
 function cleanup() {
     rm -Rf "$temp_dir"
@@ -587,8 +585,9 @@ generate_metadata() {
 
 if [ "$skip_images" == "false" ]; then
     prepare_images "${temp_dir}/images"
-    ( cd "${temp_dir}" && tar czvf images.tar.gz images  )
 fi
+( cd "${temp_dir}" && tar czvf images.tar.gz images  )
+
 cp -a "${manifests_dir}" "${temp_dir}/manifests"
 ( cd "${temp_dir}" && tar czvf "manifests.tar.gz" manifests  )
 generate_metadata "${temp_dir}/metadata.json"
@@ -600,7 +599,7 @@ mender-artifact write module-image \
     -n "$artifact_name" \
     --meta-data "${temp_dir}/metadata.json" \
     -f "${temp_dir}/manifests.tar.gz" \
-    $([ "$skip_images" == "false" ] && echo "-f ${temp_dir}/images.tar.gz") \
+    -f "${temp_dir}/images.tar.gz" \
     --software-name "$application_name" \
     $passthrough_args
 
```

What do you think about this approach?

I promise this time to follow-up faster than last time :innocent:

2025-02-25 16:37 UTC, lluiscampos commented
Hello @DamKast. I demoed today internally your feature and I received positive feedback.

One thing that we identified is that we need to sanity check the flags to make `--skip-images` incompatible with `--deep-delta`. In other words these two features are incompatible.

Let me know if you need any help with the remaining work! Thanks again.

2025-03-25 10:15 UTC, lluiscampos commented
> Result: the cleanup is not working, which means that the old images are not removed from docker. That means, If I would deploy 10 different artifacts with different images, all the images would stay on my device.
> 
> What do you think about this?

Right. But how is that different from your original proposal in this PR? There also the cleanup won't work neither, will it?

The cleanup cannot work as long as we don't send the container images in the Artifact because we can't store the information from the previous deployment and then remove them on the current one. So I would accept this as a limitation of this way of using the Update Module.

2025-03-25 11:25 UTC, DamKast commented
In my PR I added the `image_urls` array in the `generate_metadata()` function of the `gen-app` script in case the flag is set.

```
@@ -539,16 +549,28 @@ generate_metadata() {
    echo -ne '"platform":' >> "${output}"
    printf '"%s",' "$platform" >> "${output}"
    echo -ne '"version":' >> "${output}"
-    printf '"%s",' "$version" >> "${output}"
-    echo -ne '"images":[' >> "${output}"
-    for sha in $(echo "${images_shas[@]}" | tr ' ' '\n' | sort | uniq); do
-        shas+=($sha)
-    done
-    for ((i = 0; i < ${#shas[@]}; i++)); do
-        printf '"%s"' "${shas[${i}]}" >> "${output}"
-        [[ $((i + 1)) -lt ${#shas[@]} ]] && echo -ne "," >> "${output}"
-    done
-    echo -ne ']' >> "${output}"
+    printf '"%s"' "$version" >> "${output}"
+    if [ "$skip_images" == "false" ]; then
+        echo -ne ', "images":[' >> "${output}"
+        for sha in $(echo "${images_shas[@]}" | tr ' ' '\n' | sort | uniq); do
+            shas+=($sha)
+        done
+        for ((i = 0; i < ${#shas[@]}; i++)); do
+            printf '"%s"' "${shas[${i}]}" >> "${output}"
+            [[ $((i + 1)) -lt ${#shas[@]} ]] && echo -ne "," >> "${output}"
+        done
+        echo -ne ']' >> "${output}"
+    else
+        for url in $(echo "${images[@]}" | tr ' ' '\n' | sort | uniq); do
+            urls+=($url)
+        done
+        echo -ne ', "images_urls": [' >> "${output}"
+        for ((i = 0; i < ${#urls[@]}; i++)); do
+            printf '"%s"' "${urls[${i}]}" >> "${output}"
+            [[ $((i + 1)) -lt ${#urls[@]} ]] && echo -ne "," >> "${output}"
+        done
+        echo -ne ']' >> "${output}"
+    fi
    if [[ "${k8s_ctr_address}" != "" || "${k8s_namespace}" != "" ]]; then
        echo -ne ',"env":{' >> "${output}"
        echo -ne "\"K8S_CTR_ADDRESS\":\"${k8s_ctr_address}\"," >> "${output}"
```

And then in the `app` script, when installing the artifact, I create the `urls` file necessary for cleanup in the `handle_artifact()` function. You can visualize the changes under the PR "Files changed" tab better.


So, basically in my solution, the content of the metadata is different if the `--skip-image` flag is set or not.

2025-03-26 07:53 UTC, lluiscampos commented
@DamKast You are right :sob: Then we are back to the original stand point: there seems to be no way to add this feature in a less intrusive way.

@merlin-northern @jo-lund I don't know what to do with this contribution. Either we accept it as-is (minor review needed) or we conclude that it is too big of a design change and reject. I'll bring this up in our next internal meeting.

@DamKast If we reject, you can fork this repository and make your own update module. Then you wouldn't even need the `--skip-image` flag and just do such a behavior by default.

2026-03-18 09:20 UTC, danielskinstad commented
Hey, thank you again for your contribution and sorry for leaving this open for such a long time. We are going to archive this repository in favor of our newly released docker-compose Update Module. You can find the sources in https://github.com/mendersoftware/mender-container-modules. 

We currently document [Artifact creation](https://docs.mender.io/artifact-creation/create-a-docker-compose-update-artifact), and how to integrate it with [Debian](https://docs.mender.io/operating-system-updates-debian-family/customize-mender/docker-compose-support) and [Yocto](https://docs.mender.io/operating-system-updates-yocto-project/customize-mender/docker-compose-update-module).

Since we're not going to maintain this repository anymore, we will close the contributed PRs. Feel free to contribute to the new Update Module.

2026-03-18 09:20 UTC, closed without merging